check tag format

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -75,8 +75,12 @@ jobs:
         - name: Check tag format
           run: |
             node update_json.js
-          if: startsWith(${{inputs.tag}},"SP.") 
-
+          if [[ ${{ inputs.tag }} =~ ^refs/tags/SP\.[0-9]{2}\.[0-9]\.[0-9]$ ]]; then
+            echo "Tag format is valid: ${{ inputs.tag }}"
+          else
+            echo "Invalid tag format: ${{ inputs.tag }}"
+            exit 1
+          fi
             
             
             
